# Aider advanced model settings
# Docs: https://aider.chat/docs/config/adv-model-settings.html
# IMPORTANT: This file must be a YAML LIST (each item begins with a dash).
# Each list item is a dict of settings for a single model.

# Set temperature 1.0 for the main model.
- name: gpt-5-2025-08-07
  extra_params:
    temperature: 1.0
  # You can add more per-model overrides here if needed, eg:
  # edit_format: diff
  # use_repo_map: true

# (Optional) Global extra params applied to all models (uncomment to use):
# - name: aider/extra_params
#   extra_params:
#     temperature: 1.0
#     # Any other litellm completion params go here.
