###############################
# Common extensions / anchors #
###############################
# Using an OpenAPI-style custom extension key (x-common-litellm-params) purely
# as a namespaced container for shared YAML anchors. This keeps runtime config
# unchanged while removing duplication via merge keys (<<).
x-common-litellm-params: &common_litellm
  api_base: https://yunwu.ai/v1
  api_key: os.environ/YUNWU_OPENAI_KEY_6x
  temperature: 1.0

model_list:
  # Each model only specifies the differing "model" value; shared fields are merged.
  - model_name: gpt-5
    litellm_params:
      <<: *common_litellm
      model: openai/gpt-5-2025-08-07

  - model_name: gpt-4o
    litellm_params:
      <<: *common_litellm
      model: openai/gpt-4o

# Proxy settings (keep purely format/runtime flags here; avoid UI to skip DB usage)
litellm_settings:
  # Disable admin UI -> avoids DB-backed pages / migrations
  ui: false
  # Format compatibility
  openai_compatible: true
  anthropic_compatible: true
  vertex_compatible: true
  drop_params: true  # Drop unknown params instead of erroring out
  disable_token_counter: true  # Disable token counting to avoid Gemini CLI errors
  # Additional logging and error suppression settings
  set_verbose: false  # Disable verbose debug logs
  suppress_debug_info: true  # Suppress debug information

  # Gemini CLI specific settings
  callbacks: []  # Explicitly disable all callbacks
  enable_json_schema_validation: false  # Disable JSON schema validation that may interfere
  # Handle JSON requests dynamically
  modify_params: true  # Allow parameter modification
  enable_content_safety: false  # Disable content safety that might interfere

# General settings to disable database features (and supply master key)
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY   # Provide master key here (not stored in DB)
  disable_spend_logs: true                    # Do not write spend logs to DB
  disable_error_logs: true                    # Do not write error logs to DB
  disable_adding_master_key_hash_to_db: true  # Do not store master key hash in DB
  allow_requests_on_db_unavailable: true      # Start/serve even if DB missing
  disable_reset_budget: true                  # Disable scheduled budget tasks (DB)
  # Handle Gemini CLI compatibility issues
  suppress_debug_info: true                   # Reduce verbose logging
  enforce_content_safety: false               # Reduce validation that may conflict with Gemini CLI
  # Additional error suppression settings
  disable_logging_callbacks: true             # Disable all logging callbacks
  disable_response_logging: true              # Disable response logging that causes httpx_response issues
  # (No DATABASE_URL set; proxy runs statelessly.)

# Router settings for advanced configurations
router_settings:
  # Enable different endpoint formats and model group aliases
  model_group_alias:
    "gemini-2.5-pro": "gpt-5"
    "gemini-2.5-flash": "gpt-4o"
    "gemini-2.5-flash-lite": "gpt-4o"
  # Disable problematic routing features
  enable_pre_call_checks: false
  enable_load_balancing_on_error: false
  # Add JSON format handling
  enable_json_schema_validation: false
  # Allow response format override
  allowed_fails: 3
  cooldown_time: 1
  enable_anthropic_endpoint: true
  enable_vertex_endpoint: true
  enable_gemini_endpoint: true
  # Disable problematic endpoints
  disable_token_counter: true
